version: '3'
services:
  web:
    image: "registry.gitlab.kuleuven.be/distrinet/research/bughog/experiment-server:latest"
    pull_policy: never
    container_name: bh_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./experiments/pages:/experiments/pages
      - ./experiments/resources:/app/static/resources
