version: '3'
services:
  web:
    image: "registry.gitlab.kuleuven.be/distrinet/research/bughog/experiment-server"
    container_name: bh_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./custom_pages:/custom_pages
      - ./custom_resources:/app/static/custom
