version: '3'
services:
  web:
    image: "bughog/web"
    pull_policy: never
    container_name: bh_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./experiments/pages:/experiments/pages
      - ./experiments/res:/app/static/res
